{% set name = "tlars" %}
{% set version = "0.7.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: <SHA256_HASH>
  git_url: https://github.com/ArnauVilella/tlars-python.git
  git_rev: main

build:
  number: 0
  skip: true  # [py<310]

requirements:
  build:
    - {{ compiler('cxx') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}      # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11 >=2.12                        # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=42
    - wheel
    - pybind11 >=2.12
    - carma
    - numpy
    - armadillo
    - libblas
    - liblapack
    - blas-devel                             # [win]
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - tlars
    - tlars.tlars_cpp
  commands:
    - python -c "from tlars import TLARS; print('tlars imported successfully')"

about:
  home: https://github.com/ArnauVilella/tlars-python
  summary: Terminating-LARS (T-LARS) algorithm for variable selection
  description: |
    Python port of the tlars R package implementing the Terminating-LARS
    (T-LARS) algorithm. T-LARS is a fast, flexible, and scalable method for
    variable selection in high-dimensional settings using the LARS algorithm
    with early termination based on dummy variables.
  license: GPL-3.0-only
  license_file: LICENSE
  dev_url: https://github.com/ArnauVilella/tlars-python

extra:
  recipe-maintainers:
    - ArnauVilella
